### ISSUE TITLE
Restore scroll on back navigation.

### ISSUE THREAD

**Issue by quentincaffeino** [jarvis394/habra#31]
Every time I navigate back inside the app I'm being thrown to the beginning of the page.
Every time I open some link and then return back I might find myself at the end or at the start of the page, it seems random.

**Comment by quentincaffeino** [comment]
Ok, navigation inside app now remembers scroll location, but opening external link not. When returning from external link not only post position is not restored, returning back to home page also looses scroll position.

I'm using it via pwa btw.

**Comment by jarvis394** [comment]
This behavior also occur on the m.habr.com site; probably won't be fixed because it requires snapshotting the page's client scroll before window history push, which is not possible at the moment as there is no getComponentSnapshot hook in React for functional components.

**UPD:** need to test this lib - https://github.com/nanyang24/react-scroll-restoration
