### ISSUE TITLE
Love this project but I'm strongly against collecting any form of metrics

### ISSUE THREAD

**Issue by quentincaffeino** [jarvis394/habra#98]
Is there any hope that someday it would be an **opt-in** (disabled by default) option?

**Comment by jarvis394** [comment]
Probably there would be such option in v2 branch [(redesign)](https://github.com/jarvis394/habra/tree/redesign).

Anyways, I collect metrics only for page views and, in addition, on the v2 branch I use Matomo analytics instead of GA because it doesn't (hopefully) send data to third-party. I'm planning to implement Matomo analytics on a v1 branch soon.

**Comment by quentincaffeino** [comment]
I guess matomo is fine since you can fully selfhost it and in case it leaks data you can prevent that by blocking all outgoing connections.
Then at least a regular "We use cookies" banner would be enough.

**Comment by jarvis394** [comment]
> since you can fully selfhost

That's exactly what I'm doing!

<img width="350px" src="https://user-images.githubusercontent.com/37776763/116915322-872c7480-ac54-11eb-99a2-f481cdc6404f.png" />

**Comment by quentincaffeino** [comment]
Keep up the good work! Looking forward for v2!

**Comment by jarvis394** [comment]
> Looking forward for v2!

Just in case, v2 is hosted on habra.vercel.app

**Comment by quentincaffeino** [comment]
I tried it several hours ago and it was down, works right now though. Looks awesome

**Comment by jarvis394** [comment]
`v1` is going to be removed so this issue should be closed. Implemented in `v2`
